var tag = {
    // IMAGE TAGS
    IMAGE_DOWNLOADED: 50,
    IMAGE_UNDOWNLOADED: 51,

    // REDDIT TAGS
    REDDIT_QUARANTINE: 100,
    REDDIT_REMOVED: 101,
    REDDIT_PREVIEW_FORMAT: 102,
    REDDIT_THUMBNAIL_FORMAT: 103,

    // BOORU TAGS
    BOORU_DEFAULT_FORMAT: 200,
    BOORU_LARGE_FORMAT: 201,
    BOORU_PREVIEW_FORMAT: 202,
    BOORU_SAMPLE_FORMAT: 203,
    BOORU_SOURCE_FORMAT: 204
};

module.exports = Object.freeze(tag);